import type { Config } from "tailwindcss";

// NOTE: This project uses Tailwind CSS v4, which reads design tokens from
// app/globals.css via @theme blocks. This file is kept for reference and
// tooling compatibility; the authoritative token definitions are in globals.css.
const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-container": "#deed2e",
        "surface-variant": "#353629",
        "tertiary-container": "#d8e3fb",
        "primary-fixed-dim": "#c2d000",
        "surface-container-highest": "#353629",
        "on-primary-fixed": "#1b1d00",
        "error-container": "#93000a",
        "on-primary-container": "#626900",
        "on-error": "#690005",
        "on-primary": "#2f3300",
        "on-secondary-fixed": "#0d1c2d",
        "on-tertiary-container": "#5a6579",
        "primary": "#ffffff",
        "secondary-container": "#39485a",
        "on-background": "#e5e3d0",
        "inverse-on-surface": "#313124",
        "surface-container-lowest": "#0e0f05",
        "secondary-fixed-dim": "#b9c8de",
        "error": "#ffb4ab",
        "surface": "#131409",
        "on-secondary-container": "#a7b6cc",
        "primary-fixed": "#deed2e",
        "on-primary-fixed-variant": "#454b00",
        "inverse-surface": "#e5e3d0",
        "secondary-fixed": "#d4e4fa",
        "surface-bright": "#393a2d",
        "outline": "#929279",
        "surface-dim": "#131409",
        "tertiary-fixed-dim": "#bcc7de",
        "background": "#131409",
        "on-tertiary-fixed": "#111c2d",
        "on-surface": "#e5e3d0",
        "surface-tint": "#c2d000",
        "tertiary-fixed": "#d8e3fb",
        "surface-container-low": "#1c1c11",
        "surface-container-high": "#2a2b1e",
        "tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#3c475a",
        "surface-container": "#202015",
        "secondary": "#b9c8de",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#39485a",
        "outline-variant": "#474833",
        "inverse-primary": "#5c6300",
        "on-surface-variant": "#c8c8ad",
        "on-tertiary": "#263143",
        "on-secondary": "#233143",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "gutter": "24px",
        "xxl": "80px",
        "lg": "24px",
        "sm": "8px",
        "unit": "4px",
        "md": "16px",
        "xs": "4px",
        "container-max": "1280px",
        "xl": "48px",
      },
      fontFamily: {
        "display-lg": ["Space Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "data-point": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "700" }],
        "data-point": ["14px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
